docs/project-structure.md

Update project structure docs based release version actually.

docs: Update project structure based release version

---

.github/pull_request_template.md

* Create PR template to make repo conventions

chore(ci): Add PR template to make repo conventions

---

README.md
cmd/idled/main.go
docs/cost-savings-calculation.md
docs/project-structure.md
go.mod
go.sum
internal/models/lambda.go
pkg/aws/lambda.go
pkg/formatter/lambda_table.go

/kind feature
This PR adds support for detecting idle AWS Lambda functions to help identify cost-saving opportunities. It implements a complete workflow for analyzing Lambda functions across regions, determining usage patterns, and identifying functions that have minimal or no invocations.
Key features added:
- Lambda function scanning with CloudWatch metrics integration
- Idle detection based on invocation patterns and last usage time
- Cost estimation based on memory allocation, duration, and invocation count
- Real-time progress indication with function names and completion percentage
- Tabular display of Lambda functions with key metrics
- Documentation updates covering implementation and cost calculation details
This feature helps organizations identify Lambda functions that are …

feat(lambda): Add support for idle Lambda function detection

---

README.md
cmd/idled/main.go
internal/models/eip.go
pkg/aws/eip.go
pkg/aws/lambda.go
pkg/formatter/eip_table.go
pkg/formatter/lambda_table.go
pkg/utils/pointerutils.go

/kind feature
- Support idle Elastic IP scanning
- Refactor table output
- Update README docs
Fixes #

feat: Support idle Elastic IP scanning

---

README.md
cmd/idled/main.go
docs/cost-savings-calculation.md
docs/project-structure.md
go.mod
go.sum
internal/models/eip.go
internal/models/lambda.go
pkg/aws/eip.go
pkg/aws/lambda.go
pkg/formatter/eip_table.go
pkg/formatter/lambda_table.go
pkg/utils/pointerutils.go

/kind release
- Release idled 0.3.0 (previous version: 0.2.0)
- Support Elastic IP service in AWS
- Support Lambda service in AWS
Fixes #

release: idled 0.3.0

---

cmd/idled/main.go
pkg/formatter/config_table.go

/kind refactor
- Set column space from 3 to 2
- Set default service name `ec2` as const variable
Fixes #

refactor: Output table format

---

cmd/idled/main.go

/kind chore
- Update build date
- Update CLI version from 0.3.0 to 0.4.0
Fixes #

bump: Pin CLI version to 0.4.0

---

README.md
cmd/idled/main.go
docs/project-structure.md
go.mod
go.sum
internal/models/config.go
internal/models/iam.go
pkg/aws/config.go
pkg/aws/iam.go
pkg/formatter/config_table.go
pkg/formatter/iam_table.go

/kind release
- Release 0.4.0 (previous version: 0.3.0)
Fixes #

release: idled 0.4.0

---

cmd/idled/main.go

/kind bump
Bump cli version from 0.4.0 to 0.5.0
https://github.com/younsl/idled/pull/15

bump: CLI version to 0.5.0

---

README.md
cmd/idled/main.go
docs/aws/logs.md
go.mod
go.sum
internal/models/logs.go
pkg/aws/logs.go
pkg/formatter/logs_table.go

/kind feature
- Support scanning for cloudwatch logs as known as `logs`
Fixes #

feat: Support cloudwatch logs scanning

---

README.md
docs/available-services.md

/kind docs
- Add available services docs
Fixes #

docs: Add available services

---

.github/workflows/release.yml

/kind chore
- Added macOS (`darwin`) builds (`amd64`, `arm64`) to the GitHub Actions release workflow (`release.yml`).
- Updated the installation script in the release notes to dynamically detect OS (`uname -s`) and architecture (`arch`) to download the correct binary.
Fixes #
- Related file: `.github/workflows/release.yml`

chore(actions): Create release workflow supporting cross-platform 

---

cmd/idled/main.go
go.mod
go.sum
internal/models/ecr.go
pkg/aws/ecr.go
pkg/formatter/ecr.go
pkg/utils/time_utils.go

/kind feature
Support idle ECR scanning
- Add `ImageCount` field to `RepositoryInfo` model.
- Modify AWS ECR client (`pkg/aws/ecr.go`) to calculate and return the total image count per repository alongside the last push time.
- Update ECR formatter (`pkg/formatter/ecr.go`) to display the image count in a new "TOTAL IMAGE" column in the output table.
Fixes #

feat(ecr): Support idle ECR scanning

---

docs/available-services.md
docs/aws/ecr.md
docs/aws/logs.md

/kind documentation
This PR includes documentation changes
- Add ECR service to available service lists
- Add scan rationale for CloudWatch Logs
Fixes #

docs: Add ECR to available service lists

---

.github/workflows/release.yml
cmd/idled/main.go

/kind bugfix
Delivery missing codes for new version info at 0.7.0
Fixes #
- #27

fix: backport missing in release 0.7.0

---

internal/models/lambda.go
pkg/aws/lambda.go
pkg/formatter/lambda_table.go

- Analyze `TRIGGER` column as a bool type in AWS Lambda function scanning
Fixes #

feat(lambda): Add TRIGGER column

---

docs/aws/lambda.md

/kind documentation
- Update documentation for lambda service to fit release 0.7.1
Fixes #
- #29

docs: Update lambda cost model and outputs

---

cmd/idled/main.go

/kind bump
- Bump CLI version info from 0.7.0 to 0.7.1
Fixes #

bump: cli version info from 0.7.0 to 0.7.1

---

.github/workflows/release.yml
Makefile
cmd/idled/main.go
internal/version/version.go

/kind release
- Release idled 0.7.2 (previous version: 0.7.1)
Fixes #

release: idled 0.7.2

---

pkg/aws/msk.go
pkg/formatter/msk_table.go

/kind refactor
- Leverage centralized spinner code in main.go rather than msk dedicated code
- Align output table columns for MSK scanner
- Delete unnecessary codes
Fixes #

refactor(msk): Leverage centralized spinner code and align output

---

LICENSE

/kind chore
- Create `LICENSE` file to grant MIT License explictly.
Fixes #

chore: Create LICENSE file
